### PR TITLE
[ODST-218] Update AB Proxy URLs

### PR DESCRIPTION
**Pull request by stephenfuqua**

### CODE REVIEW

**Comment by stephenfuqua** [comment]
This is a duplicate PR.

**Comment by gidabinst** [comment]
@stephenfuqua Not sure how this was closed as a duplicate if the contents of it were never merged into main. Anyway, should I open a new pull request if I want these changes to be merged?

**Comment by stephenfuqua** [comment]
#12 is the "duplicate".  I'm taking another look to see if that was just a mistake on my part.

**Comment by stephenfuqua** [comment]
I see the mistake I made now. #12 was a merge from a fork into a feature branch. This PR is from the feature branch into `main`.

**Review by jasonh-edfi — APPROVED** [review]
Reviewed and approved as needed URL changes.

**Pull request merged**
